FROM node:20-bookworm-slim
WORKDIR /app

# Install production dependencies
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund

# Copy source
COPY . .

EXPOSE 4000

# Start server
CMD ["node", "src/server.js"]
